on:
  push:
    branches:
      - main
      - staging

env:
  BRANCH_NAME: ${{ forgejo.head_ref || forgejo.ref_name }}

jobs:
  build:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - name: Get tag name
        shell: bash
        id: get_tag_name
        run: |
          case "$BRANCH_NAME" in
            "main")
              echo "latest_tag=latest" ;;
            "staging")
              echo "latest_tag=staging" ;;
            *)
              echo "Unhandled branch: $BRANCH_NAME"
              exit 1 ;;
          esac >> $FORGEJO_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: https://git.int.pfarley.dev
          username: ${{ forge.actor }}
          password: ${{ secrets.PACKAGE_REPO_KEY }}
      - name: Build and Push - ${{ env.BRANCH_NAME }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: git.int.pfarley.dev/pfarley-private/blog:${{ steps.get_tag_name.outputs.latest_tag }}

      - name: Deploy
        uses: https://git.int.pfarley.dev/pfarley/portainer-update-stack-action@main
        with:
          portainer-url: ${{ secrets.PORTAINER_URL }}
          portainer-api-key: ${{ secrets.PORTAINER_API_KEY }}
          portainer-endpoint: 13
          portainer-stack: 62
